### PR TITLE
ibc-types: amend `DomainType` marker trait and serde feature

### PR DESCRIPTION
**Pull request by erwanor**
Even though the workspace compiles when running `cargo build`, individual crate do not. As a result, it is not possible at this time to publish the crates to `crates.io`. 

This PR is a tentative pass at fixing those errors. To reproduce the error easily, you can download: `cargo install cargo-all-features` and then run `cargo check-all-features` from the root directory.

```
error[E0277]: the trait bound `error::Error: core::error::Error` is not satisfied
  --> crates/ibc-types-core-client/src/msgs/create_client.rs:24:6
   |
24 | impl DomainType for MsgCreateClient {
   |      ^^^^^^^^^^ the trait `core::error::Error` is not implemented for `error::Error`
   |
   = note: required for `anyhow::Error` to implement `core::convert::From<error::Error>`
   = note: required for `error::Error` to implement `core::convert::Into<anyhow::Error>`
note: required by a bound in `DomainType`
  --> /Users/user/prod/ibc-types/crates/ibc-types-domain-type/src/lib.rs:22:44
   |
22 |     <Self as TryFrom<Self::Proto>>::Error: Into<anyhow::Error> + Send + Sync + 'static,
   |                                            ^^^^^^^^^^^^^^^^^^^ required by this bound in `DomainType`

error[E0277]: the trait bound `error::Error: core::error::Error` is not satisfied
  --> crates/ibc-types-core-client/src/msgs/misbehaviour.rs:26:6
   |
26 | impl DomainType for MsgSubmitMisbehaviour {
   |      ^^^^^^^^^^ the trait `core::error::Error` is not implemented for `error::Error`
   |
   = note: required for `anyhow::Error` to implement `core::convert::From<error::Error>`
   = note: required for `error::Error` to implement `core::convert::Into<anyhow::Error>`
note: required by a bound in `DomainType`
  --> /Users/user/prod/ibc-types/crates/ibc-types-domain-type/src/lib.rs:22:44
   |
22 |     <Self as TryFrom<Self::Proto>>::Error: Into<anyhow::Error> + Send + Sync + 'static,
   |                                            ^^^^^^^^^^^^^^^^^^^ required by this bound in `DomainType`

error[E0277]: the trait bound `error::Error: core::error::Error` is not satisfied
  --> crates/ibc-types-core-client/src/msgs/update_client.rs:24:6
   |
24 | impl DomainType for MsgUpdateClient {
   |      ^^^^^^^^^^ the trait `core::error::Error` is not implemented for `error::Error`
   |
   = note: required for `anyhow::Error` to implement `core::convert::From<error::Error>`
   = note: required for `error::Error` to implement `core::convert::Into<anyhow::Error>`
note: required by a bound in `DomainType`
  --> /Users/user/prod/ibc-types/crates/ibc-types-domain-type/src/lib.rs:22:44
   |
22 |     <Self as TryFrom<Self::Proto>>::Error: Into<anyhow::Error> + Send + Sync + 'static,
   |                                            ^^^^^^^^^^^^^^^^^^^ required by this bound in `DomainType`

error[E0277]: the trait bound `error::Error: core::error::Error` is not satisfied
  --> crates/ibc-types-core-client/src/msgs/upgrade_client.rs:41:6
   |
41 | impl DomainType for MsgUpgradeClient {
   |      ^^^^^^^^^^ the trait `core::error::Error` is not implemented for `error::Error`
   |
   = note: required for `anyhow::Error` to implement `core::convert::From<error::Error>`
   = note: required for `error::Error` to implement `core::convert::Into<anyhow::Error>`
note: required by a bound in `DomainType`
  --> /Users/user/prod/ibc-types/crates/ibc-types-domain-type/src/lib.rs:22:44
   |
22 |     <Self as TryFrom<Self::Proto>>::Error: Into<anyhow::Error> + Send + Sync + 'static,
   |                                            ^^^^^^^^^^^^^^^^^^^ required by this bound in `DomainType`
   ```

The errors remain but at least each crate can now be built individually using its respective default features. (`check_crates.sh` and `check_build.sh`)

### CODE REVIEW

File: crates/ibc-types-identifier/Cargo.toml [hunk 1]
```diff
@@ -23,6 +23,7 @@ std = [
     "serde/std",
     "displaydoc/std",
 ]
+with_serde = ["serde", "serde_derive"]
```
Comment (erwanor) [inline crates/ibc-types-identifier/Cargo.toml:26]: weirdly enough, aliasing the dep tree: `serde = ["dep:serde", "dep:serde_derive"]` was not sufficient, the compiler was not able to resolve the `serde::Serialize` dependency on `IdentifierMsg`, ditto elsewhere.
